"""Fixing relationships between models

Revision ID: d881b37790cb
Revises: 0d89a6ecc859
Create Date: 2025-01-18 00:24:10.534601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd881b37790cb'
down_revision: Union[str, None] = '0d89a6ecc859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
